version: "3"

services:
  mc:
    # Only using IMAGE variable to allow for local testing
    image: ${IMAGE:-itzg/minecraft-server}
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      SPIGET_RESOURCES: 9089,34315,3836
    volumes:
      - data:/data

volumes:
  data: {}
