name: Generate README table of contents
on:
  push:
    branches:
      - master
    paths:
      - README.md
jobs:
  generate:
    if: github.repository == 'itzg/docker-minecraft-server'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup README.md
      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "docs: Auto update markdown TOC"